### ISSUE TITLE
Incomplete K8 cluster bringup using Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ghost** [jascott1/arboreal#7]
Hi, 

I'm using a fork of the upstream arboreal repo to run the deploy-k8s playbook. Instructions how I configured Ubuntu Server 16.04 LTS before running the Ansible playbook are available [ here.](https://docs.google.com/document/d/1HlEoMN5pKbQFecp6aMhKA_zMzsBVB8usSQALbzREDFI/edit?ts=59e902c7#). The repo fork I'm using you can find [here. ](https://github.com/uhofemei/resilient-edge) The outcome is an error message related to Ceph not being able to deploy. The nodes are specified in the inventory file of the resilient-edge repository. 

I don't think Ceph not being able to deploy is unrelated to the fact that Kubernetes nods cannot join the cluster.

Please take a look at your playbooks and make sure they work with standard Ubuntu Server 16.04 LTS. At this point this is not the case. 
 
The Ansible error message I see states this:

  ]  overwrite_conf                : False\n[ceph_deploy.cli][INFO  ]  subcommand                    : create\n[ceph_deploy.cli][INFO  ]  dmcrypt_key_dir               : /etc/ceph/dmcrypt-keys\n[ceph_deploy.cli][INFO  ]  quiet                         : False\n[ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x7fb0e6d094d0>\n[ceph_deploy.cli][INFO  ]  cluster                       : ceph\n[ceph_deploy.cli][INFO  ]  fs_type                       : xfs\n[ceph_deploy.cli][INFO  ]  func                          : <function osd at 0x7fb0e6f59d70>\n[ceph_deploy.cli][INFO  ]  ceph_conf                     : None\n[ceph_deploy.cli][INFO  ]  default_release               : False\n[ceph_deploy.cli][INFO  ]  zap_disk                      : False\n[ceph_deploy.osd][DEBUG ] Preparing cluster ceph disks loadbalancer:/dev/vdb:\n[loadbalancer][DEBUG ] connection detected need for sudo\n[loadbalancer][DEBUG ] connected to host: loadbalancer \n[loadbalancer][DEBUG ] detect platform information from remote host\n[loadbalancer][DEBUG ] detect machine type\n[loadbalancer][DEBUG ] find the location of an executable\n[ceph_deploy.osd][INFO  ] Distro info: Ubuntu 16.04 xenial\n[ceph_deploy.osd][DEBUG ] Deploying osd to loadbalancer\n[loadbalancer][DEBUG ] write cluster configuration to /etc/ceph/{cluster}.conf\n[ceph_deploy.osd][DEBUG ] Preparing host loadbalancer disk /dev/vdb journal None activate True\n[loadbalancer][DEBUG ] find the location of an executable\n[loadbalancer][INFO  ] Running command: sudo /usr/sbin/ceph-disk -v prepare --cluster ceph --fs-type xfs -- /dev/vdb\n[loadbalancer][WARNING] Traceback (most recent call last):\n[loadbalancer][WARNING]   File \"/usr/sbin/ceph-disk\", line 9, in <module>\n[loadbalancer][WARNING]     load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5096, in run\n[loadbalancer][WARNING]     main(sys.argv[1:])\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5047, in main\n[loadbalancer][WARNING]     args.func(args)\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 1855, in main\n[loadbalancer][WARNING]     Prepare.factory(args).prepare()\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 1851, in factory\n[loadbalancer][WARNING]     return PrepareFilestore(args)\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 1863, in __init__\n[loadbalancer][WARNING]     self.data = PrepareFilestoreData(args)\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 2468, in __init__\n[loadbalancer][WARNING]     self.set_type()\n[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 2476, in set_type\n[loadbalancer][WARNING]     dmode = os.stat(self.args.data).st_mode\n[loadbalancer][WARNING] OSError: [Errno 2] No such file or directory: '/dev/vdb'\n[loadbalancer][ERROR ] RuntimeError: command returned non-zero exit status: 1\n[ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-disk -v prepare --cluster ceph --fs-type xfs -- /dev/vdb\n[ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs", "stderr_lines": ["[ceph_deploy.conf][DEBUG ] found configuration file at: /home/ceph-deploy/.cephdeploy.conf", "[ceph_deploy.cli][INFO  ] Invoked (1.5.32): /usr/bin/ceph-deploy osd create loadbalancer:vdb", "[ceph_deploy.cli][INFO  ] ceph-deploy options:", "[ceph_deploy.cli][INFO  ]  username                      : None", "[ceph_deploy.cli][INFO  ]  disk                          : [('loadbalancer', '/dev/vdb', None)]", "[ceph_deploy.cli][INFO  ]  dmcrypt                       : False", "[ceph_deploy.cli][INFO  ]  verbose                       : False", "[ceph_deploy.cli][INFO  ]  bluestore                     : None", "[ceph_deploy.cli][INFO  ]  overwrite_conf                : False", "[ceph_deploy.cli][INFO  ]  subcommand                    : create", "[ceph_deploy.cli][INFO  ]  dmcrypt_key_dir               : /etc/ceph/dmcrypt-keys", "[ceph_deploy.cli][INFO  ]  quiet                         : False", "[ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x7fb0e6d094d0>", "[ceph_deploy.cli][INFO  ]  cluster                       : ceph", "[ceph_deploy.cli][INFO  ]  fs_type                       : xfs", "[ceph_deploy.cli][INFO  ]  func                          : <function osd at 0x7fb0e6f59d70>", "[ceph_deploy.cli][INFO  ]  ceph_conf                     : None", "[ceph_deploy.cli][INFO  ]  default_release               : False", "[ceph_deploy.cli][INFO  ]  zap_disk                      : False", "[ceph_deploy.osd][DEBUG ] Preparing cluster ceph disks loadbalancer:/dev/vdb:", "[loadbalancer][DEBUG ] connection detected need for sudo", "[loadbalancer][DEBUG ] connected to host: loadbalancer ", "[loadbalancer][DEBUG ] detect platform information from remote host", "[loadbalancer][DEBUG ] detect machine type", "[loadbalancer][DEBUG ] find the location of an executable", "[ceph_deploy.osd][INFO  ] Distro info: Ubuntu 16.04 xenial", "[ceph_deploy.osd][DEBUG ] Deploying osd to loadbalancer", "[loadbalancer][DEBUG ] write cluster configuration to /etc/ceph/{cluster}.conf", "[ceph_deploy.osd][DEBUG ] Preparing host loadbalancer disk /dev/vdb journal None activate True", "[loadbalancer][DEBUG ] find the location of an executable", "[loadbalancer][INFO  ] Running command: sudo /usr/sbin/ceph-disk -v prepare --cluster ceph --fs-type xfs -- /dev/vdb", "[loadbalancer][WARNING] Traceback (most recent call last):", "[loadbalancer][WARNING]   File \"/usr/sbin/ceph-disk\", line 9, in <module>", "[loadbalancer][WARNING]     load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5096, in run", "[loadbalancer][WARNING]     main(sys.argv[1:])", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 5047, in main", "[loadbalancer][WARNING]     args.func(args)", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 1855, in main", "[loadbalancer][WARNING]     Prepare.factory(args).prepare()", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 1851, in factory", "[loadbalancer][WARNING]     return PrepareFilestore(args)", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 1863, in __init__", "[loadbalancer][WARNING]     self.data = PrepareFilestoreData(args)", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 2468, in __init__", "[loadbalancer][WARNING]     self.set_type()", "[loadbalancer][WARNING]   File \"/usr/lib/python2.7/dist-packages/ceph_disk/main.py\", line 2476, in set_type", "[loadbalancer][WARNING]     dmode = os.stat(self.args.data).st_mode", "[loadbalancer][WARNING] OSError: [Errno 2] No such file or directory: '/dev/vdb'", "[loadbalancer][ERROR ] RuntimeError: command returned non-zero exit status: 1", "[ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-disk -v prepare --cluster ceph --fs-type xfs -- /dev/vdb", "[ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/home/demouser/git/resilient-edge/deploy-k8s.retry

PLAY RECAP ***********************************************************************************************************************************************************************
192.168.2.117              : ok=69   changed=53   unreachable=0    failed=1   
192.168.2.124              : ok=34   changed=25   unreachable=0    failed=0   
192.168.2.126              : ok=34   changed=25   unreachable=0    failed=0   

demouser@loadbalancer:~/git/resilient-edge$ kube
kubeadm  kubectl  kubelet  
demouser@loadbalancer:~/git/resilient-edge$ kube
kubeadm  kubectl  kubelet  
demouser@loadbalancer:~/git/resilient-edge$ kubectl get nodes
NAME           STATUS    AGE       VERSION
loadbalancer   Ready     8m        v1.7.5

**Comment by ghost** [comment]
Any update on this one? Thanks :)

**Comment by jascott1** [comment]
We discussed this offline. Ceph was not required for your use case and can be disabled in all_vars.yaml be setting `dynamic_provisioning: False`. Closing this issue but feel free to re-open with non-ceph error message.
